### PR TITLE
[15.0][MIG] endpoint_route_handler

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review

**Review by simahawk — APPROVED** [review]
LG

**Comment by simahawk** [comment]
@astirpe I forgot to mention that there's a fix in v14 for some edge cases https://github.com/OCA/web-api/pull/37
I'll fwd port for v16, can you take care for v15? You can update this PR if you prefer :wink:

**Pull request closed without merging**
