### PR TITLE
[MIG] endpoint_auth_api_key: Migrate to version 16.0

### PR DESCRIPTION
**Pull request by sonhd91**
Depended on:
* https://github.com/OCA/server-auth/pull/544

### CODE REVIEW

**Review by simahawk — COMMENTED** [review]
LG

**Review by cyrilmanuel — APPROVED** [review]
LGTM until failing test

**Comment by sonhd91** [comment]
> LGTM until failing test

Dependency commit removed, all main tests is passed

**Review by cyrilmanuel — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Pull request merged**
